In [1]:
import pandas as pd

In [2]:
import json

In [5]:
df = pd.read_json("C:\\Users\\emily\\OneDrive\\Desktop\\Data Science Bootcamp\\wk4\\LHL-Project-3\\drive-download-20230205T225545Z-001\\weekly_earnings.json")

ValueError: Mixing dicts with non-Series may lead to ambiguous ordering.

In [6]:
df = pd.read_csv("csv_maybe.csv")

FileNotFoundError: [Errno 2] No such file or directory: 'csv_maybe.csv'

In [9]:
df = pd.read_json("weekly_earnings_mod.json")

In [10]:
df

                                                  data
0    [5554, 8D0D0120-53D5-4A3D-B68F-D5BAFA1B9F24, 5...
1    [5555, B8156EED-2420-4B71-A56C-57DED1FA7CEC, 5...
2    [5556, A8D7795E-40FA-4923-AB52-CA8536DAAD7A, 5...
3    [5557, 8373DAD3-2886-4DAD-AFE8-84DB8C0F414E, 5...
4    [5558, 05DB3E97-35EC-4F75-891B-3F6C696CDEE0, 5...
..                                                 ...
167  [5721, 929B44CE-29DA-42D8-B7C3-C87C70D4C383, 5...
168  [5722, F8CF4AB6-378A-4075-8BE7-6195EE417848, 5...
169  [5723, F7A31164-A7FE-467F-A9F7-8A06954FB391, 5...
170  [5724, 58A68982-BF09-4DA2-9C86-094D9F52BB8F, 5...
171  [5725, 21789CE9-CD5C-4B1F-BAFF-B3D7C45E6F25, 5...

[172 rows x 1 columns]

In [15]:
df2 = pd.read_json("weekly_earnings_mod2.json")
df2.columns = ["sid", "id", "position", "created_at", "created_meta", "updated_at", "updated_meta", "meta", 
"When", "NAICS", "Alberta", "British_Columbia", "Canada", "Manitoba", "New_Brunswick", "Newfoundland_And_Labrador", 
"Nova_Scotia", "Ontario", "Prince_Edward_Island", "Quebec", "Saskatchewan"]
df2.head()

,sid,id,position,created_at,created_meta,updated_at,updated_meta,meta,When,NAICS,...,British_Columbia,Canada,Manitoba,New_Brunswick,Newfoundland_And_Labrador,Nova_Scotia,Ontario,Prince_Edward_Island,Quebec,Saskatchewan
0,5554,8D0D0120-53D5-4A3D-B68F-D5BAFA1B9F24,5554,1435599444,710753,1435599444,710753,NaN,2001-01-01T00:00:00,Industrial aggregate excluding unclassified bu...,...,660.48,658.02,578.95,584.75,594.00,571.28,698.57,535.65,624.81,596.53
1,5555,B8156EED-2420-4B71-A56C-57DED1FA7CEC,5555,1435599444,710753,1435599444,710753,NaN,2001-02-01T00:00:00,Industrial aggregate excluding unclassified bu...,...,659.33,655.79,580.63,585.11,591.92,570.06,693.69,532.02,623.93,595.09
2,5556,A8D7795E-40FA-4923-AB52-CA8536DAAD7A,5556,1435599444,710753,1435599444,710753,NaN,2001-03-01T00:00:00,Industrial aggregate excluding unclassified bu...,...,654.07,655.88,578.67,584.13,593.47,570.70,697.08,534.71,622.94,589.09
3,5557,8373DAD3-2886-4DAD-AFE8-84DB8C0F414E,5557,1435599444,710753,1435599444,710753,NaN,2001-04-01T00:00:00,Industrial aggregate excluding unclassified bu...,...,657.15,654.09,576.36,580.92,591.96,568.70,693.73,522.50,619.12,589.37
4,5558,05DB3E97-35EC-4F75-891B-3F6C696CDEE0,5558,1435599444,710753,1435599444,710753,NaN,2001-05-01T00:00:00,Industrial aggregate excluding unclassified bu...,...,653.23,650.02,571.84,578.44,588.19,567.96,688.27,522.31,618.90,587.41

In [22]:
df2 = df2.drop("position", axis=1)

KeyError: "['position'] not found in axis"

In [26]:
df2 = df2.drop(["id", "created_at", "created_meta", "updated_at", "updated_meta", "meta"], axis=1)

df2.head()

,sid,When,NAICS,Alberta,British_Columbia,Canada,Manitoba,New_Brunswick,Newfoundland_And_Labrador,Nova_Scotia,Ontario,Prince_Edward_Island,Quebec,Saskatchewan
0,5554,2001-01-01T00:00:00,Industrial aggregate excluding unclassified bu...,670.54,660.48,658.02,578.95,584.75,594.00,571.28,698.57,535.65,624.81,596.53
1,5555,2001-02-01T00:00:00,Industrial aggregate excluding unclassified bu...,670.52,659.33,655.79,580.63,585.11,591.92,570.06,693.69,532.02,623.93,595.09
2,5556,2001-03-01T00:00:00,Industrial aggregate excluding unclassified bu...,668.49,654.07,655.88,578.67,584.13,593.47,570.70,697.08,534.71,622.94,589.09
3,5557,2001-04-01T00:00:00,Industrial aggregate excluding unclassified bu...,671.71,657.15,654.09,576.36,580.92,591.96,568.70,693.73,522.50,619.12,589.37
4,5558,2001-05-01T00:00:00,Industrial aggregate excluding unclassified bu...,664.45,653.23,650.02,571.84,578.44,588.19,567.96,688.27,522.31,618.90,587.41

In [29]:
df2.to_csv("C:\\Users\\emily\\OneDrive\\Desktop\\earnings_df.csv", index=False)